/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package umag.vista;

/**
 *
 * @author Castillo
 */
public class FormMascota extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMascota.class.getName());

    /**
     * Creates new form FormMascota
     */
    public FormMascota() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtEdad = new javax.swing.JTextField();
        txtID = new javax.swing.JTextField();
        txtRaza = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        lblNombre = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        lblInformacionmedica = new javax.swing.JLabel();
        lblRaza = new javax.swing.JLabel();
        lblEspecie = new javax.swing.JLabel();
        txtEspecie = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaInformacionmedica = new javax.swing.JTextArea();
        lblPeso = new javax.swing.JLabel();
        txtPeso = new javax.swing.JTextField();
        lblID = new javax.swing.JLabel();
        btnRegistrarMascota = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(242, 242, 211));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Datos Mascota");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(200, 20, 150, 30);
        getContentPane().add(txtEdad);
        txtEdad.setBounds(90, 150, 130, 22);
        getContentPane().add(txtID);
        txtID.setBounds(90, 270, 130, 22);
        getContentPane().add(txtRaza);
        txtRaza.setBounds(90, 110, 130, 22);

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(90, 70, 130, 22);

        lblNombre.setText("Nombre");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(30, 70, 60, 16);

        lblEdad.setText("Edad");
        getContentPane().add(lblEdad);
        lblEdad.setBounds(30, 150, 37, 16);

        lblInformacionmedica.setText("Información médica");
        getContentPane().add(lblInformacionmedica);
        lblInformacionmedica.setBounds(30, 320, 140, 20);

        lblRaza.setText("Raza");
        getContentPane().add(lblRaza);
        lblRaza.setBounds(30, 110, 37, 16);

        lblEspecie.setText("Especie");
        getContentPane().add(lblEspecie);
        lblEspecie.setBounds(30, 190, 60, 20);
        getContentPane().add(txtEspecie);
        txtEspecie.setBounds(90, 190, 130, 22);

        txtaInformacionmedica.setColumns(20);
        txtaInformacionmedica.setRows(5);
        jScrollPane1.setViewportView(txtaInformacionmedica);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 340, 480, 86);

        lblPeso.setText("Peso");
        getContentPane().add(lblPeso);
        lblPeso.setBounds(30, 230, 60, 20);
        getContentPane().add(txtPeso);
        txtPeso.setBounds(90, 230, 130, 22);

        lblID.setText("ID");
        getContentPane().add(lblID);
        lblID.setBounds(30, 270, 60, 20);

        btnRegistrarMascota.setText("Registrar Mascota");
        btnRegistrarMascota.addActionListener(this::btnRegistrarMascotaActionPerformed);
        getContentPane().add(btnRegistrarMascota);
        btnRegistrarMascota.setBounds(350, 70, 130, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegistrarMascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarMascotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarMascotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormMascota().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrarMascota;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEspecie;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblInformacionmedica;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblPeso;
    private javax.swing.JLabel lblRaza;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEspecie;
    private javax.swing.JTextField txtID;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPeso;
    private javax.swing.JTextField txtRaza;
    private javax.swing.JTextArea txtaInformacionmedica;
    // End of variables declaration//GEN-END:variables
}
