/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package umag.vista;

/**
 *
 * @author Castillo
 */
public class FormMenu extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormMenu.class.getName());

    /**
     * Creates new form FormRegistro
     */
    public FormMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        label2 = new javax.swing.JLabel();
        btnIrCliente = new javax.swing.JButton();
        btnIrPrestador = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label2.setText("PetCare");

        btnIrCliente.setText("Registrar como Cliente");
        btnIrCliente.addActionListener(this::btnIrClienteActionPerformed);

        btnIrPrestador.setText("Registrar como Prestador");
        btnIrPrestador.addActionListener(this::btnIrPrestadorActionPerformed);

        jButton2.setText("Crear nueva Solicitud (Cliente");

        jButton3.setText("Atender solicitudes (Prestador");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(187, 187, 187)
                        .addComponent(label2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(btnIrCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton2)))
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3)
                            .addComponent(btnIrPrestador))))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(label2)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnIrCliente)
                    .addComponent(btnIrPrestador))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(143, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIrClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrClienteActionPerformed
    FormCliente ventanaCliente = new FormCliente();
    
    // 2. Hacer que la ventana sea visible
    ventanaCliente.setVisible(true);
    
    // 3. Centrar la ventana en la pantalla (Opcional pero recomendado)
    ventanaCliente.setLocationRelativeTo(null);
    
    // 4. Cerrar u ocultar la ventana de menú actual para que no estorbe
    this.dispose();        
    }//GEN-LAST:event_btnIrClienteActionPerformed

    private void btnIrPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIrPrestadorActionPerformed
    FormPrestador ventanaPrestador = new FormPrestador();
    
    // 2. Hacer que la ventana sea visible
    ventanaPrestador.setVisible(true);
    
    // 3. Centrar la ventana en la pantalla
    ventanaPrestador.setLocationRelativeTo(null);
    
    // 4. Ocultar la ventana actual
    this.dispose();    }//GEN-LAST:event_btnIrPrestadorActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(() -> {
        new FormMenu().setVisible(true);
    });
}
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIrCliente;
    private javax.swing.JButton btnIrPrestador;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel label2;
    // End of variables declaration//GEN-END:variables
}
