/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package umag.vista;

/**
 *
 * @author LENOVO
 */
public class FormPrestador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormPrestador.class.getName());

    /**
     * Creates new form FormPrestador
     */
    public FormPrestador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblMascota = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblMetododepago = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        txtMascota = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtMetododepago = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btnRegistrardatos = new javax.swing.JButton();
        txtId1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Tiposervicio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Descripcionservicio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Precioservicio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Duracionservicio = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Servicios");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(440, 10, 140, 25);

        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(80, 50, 50, 16);

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(130, 40, 200, 30);

        lblEmail.setText("Email:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(90, 200, 40, 20);

        txtTelefono.addActionListener(this::txtTelefonoActionPerformed);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(130, 302, 180, 30);

        lblId.setText("Id:");
        getContentPane().add(lblId);
        lblId.setBounds(100, 90, 30, 20);

        lblMascota.setText("Cedula:");
        getContentPane().add(lblMascota);
        lblMascota.setBounds(80, 170, 50, 20);

        lblTelefono.setText("Telefono:");
        getContentPane().add(lblTelefono);
        lblTelefono.setBounds(70, 310, 80, 20);

        lblMetododepago.setText("banco:");
        getContentPane().add(lblMetododepago);
        lblMetododepago.setBounds(90, 270, 110, 10);

        lblDireccion.setText("Direccion:");
        getContentPane().add(lblDireccion);
        lblDireccion.setBounds(70, 230, 60, 20);

        lblEdad.setText("Edad:");
        getContentPane().add(lblEdad);
        lblEdad.setBounds(90, 130, 30, 20);
        getContentPane().add(txtMascota);
        txtMascota.setBounds(130, 160, 160, 30);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(130, 200, 190, 22);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(130, 230, 190, 22);
        getContentPane().add(txtEdad);
        txtEdad.setBounds(130, 120, 60, 30);
        getContentPane().add(txtMetododepago);
        txtMetododepago.setBounds(130, 260, 130, 30);

        jLabel2.setText("Disponibilidad:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 360, 90, 16);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(130, 340, 320, 60);

        btnRegistrardatos.setText("Registrar datos");
        btnRegistrardatos.addActionListener(this::btnRegistrardatosActionPerformed);
        getContentPane().add(btnRegistrardatos);
        btnRegistrardatos.setBounds(520, 343, 130, 30);
        getContentPane().add(txtId1);
        txtId1.setBounds(130, 80, 150, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Datos Prestador");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(170, 10, 140, 20);
        getContentPane().add(Tiposervicio);
        Tiposervicio.setBounds(480, 40, 150, 30);

        jLabel4.setText("Tipo de servicio:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(390, 50, 100, 16);

        jLabel5.setText("Descripcion del servicio:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(340, 100, 140, 16);
        getContentPane().add(Descripcionservicio);
        Descripcionservicio.setBounds(480, 90, 150, 30);

        jLabel6.setText("Precio del servicio:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 150, 110, 16);
        getContentPane().add(Precioservicio);
        Precioservicio.setBounds(480, 140, 150, 30);

        jLabel7.setText("Duracion del servicio (Hora):");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(360, 190, 160, 16);
        getContentPane().add(Duracionservicio);
        Duracionservicio.setBounds(520, 180, 150, 40);

        jButton1.setText("Volver al Menu");
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1);
        jButton1.setBounds(640, 10, 109, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegistrardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrardatosActionPerformed
       try {
        // ==========================================================
        // 1. CAPTURAR DATOS DEL SERVICIO
        // ==========================================================
        String tipoServicio = Tiposervicio.getText();
        String descServicio = Descripcionservicio.getText();
        int precioBaseServicio = Integer.parseInt(Precioservicio.getText());
        int duracionServicio = Integer.parseInt(Duracionservicio.getText());

        umag.modelo.entidad.Servicio nuevoServicio = new umag.modelo.entidad.Servicio(
            tipoServicio, descServicio, precioBaseServicio, duracionServicio
        );

        // ==========================================================
        // 2. CAPTURAR DATOS DEL PRESTADOR (Usando Long para evitar caídas)
        // ==========================================================
        String idPrestador = txtId1.getText();
        long cedulaPrestador = Long.parseLong(txtMascota.getText());     // <-- Cambiado a Long.parseLong
        long telefonoPrestador = Long.parseLong(txtTelefono.getText()); // <-- Cambiado a Long.parseLong
        int edadPrestador = Integer.parseInt(txtEdad.getText());
        String nombrePrestador = txtNombre.getText();
        String emailPrestador = txtEmail.getText();
        String direccionPrestador = txtDireccion.getText();
        String bancoPrestador = txtMetododepago.getText();           
        
        boolean disponibilidadPrestador = !jTextArea1.getText().trim().isEmpty();

        // ==========================================================
        // 3. ENVIAR AL CONTROLADOR
        // ==========================================================
        umag.control.ControlPrestador cp = new umag.control.ControlPrestador();
        
        boolean registrado = cp.guardarPrestador(
            idPrestador, cedulaPrestador, telefonoPrestador, edadPrestador, nombrePrestador, 
            emailPrestador, direccionPrestador, bancoPrestador, disponibilidadPrestador, nuevoServicio
        );

        // ==========================================================
        // 4. RETROALIMENTACIÓN
        // ==========================================================
        if (registrado) {
            javax.swing.JOptionPane.showMessageDialog(this, "¡Prestador y Servicio guardados exitosamente!");
            
            // Limpieza de campos
            Tiposervicio.setText("");
            Descripcionservicio.setText("");
            Precioservicio.setText("");
            Duracionservicio.setText("");
            txtNombre.setText("");
            txtId1.setText("");
            txtEdad.setText("");
            txtMascota.setText("");
            txtEmail.setText("");
            txtDireccion.setText("");
            txtMetododepago.setText("");
            txtTelefono.setText("");
            jTextArea1.setText("");
            new FormAtenderSolicitudes().setVisible(true); // Abre la ventana del Prestador
            this.dispose(); // Cierra el FormPrestador
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No se pudo escribir en el archivo .dat.", "Error de Almacenamiento", javax.swing.JOptionPane.ERROR_MESSAGE);
        }

    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(this, 
            "Error de formato: Revisa que los campos numéricos no tengan letras o espacios.", 
            "Error de Entrada", 
            javax.swing.JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnRegistrardatosActionPerformed

    private void txtTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTelefonoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        FormMenu menu = new FormMenu(); 
menu.setVisible(true); // Muestra el menú
this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormPrestador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Descripcionservicio;
    private javax.swing.JTextField Duracionservicio;
    private javax.swing.JTextField Precioservicio;
    private javax.swing.JTextField Tiposervicio;
    private javax.swing.JButton btnRegistrardatos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMascota;
    private javax.swing.JLabel lblMetododepago;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtMascota;
    private javax.swing.JTextField txtMetododepago;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
