/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package umag.vista;

/**
 *
 * @author Castillo
 */
public class FormSolicitud extends javax.swing.JPanel {

    /**
     * Creates new form FormSolicitud
     */
    public FormSolicitud() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        label2 = new javax.swing.JLabel();
        txtIdSolicitud = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtIdCliente = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtIdPrestador = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtComentario = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        label3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtConsultaId = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTextField1.setText("jTextField1");

        label2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label2.setText("Solicitudes");

        jLabel1.setText("Id:");

        jLabel2.setText("Id Cliente:");

        jLabel3.setText("Id Prestador:");

        txtIdPrestador.addActionListener(this::txtIdPrestadorActionPerformed);

        jLabel4.setText("Comentarios:");

        btnRegistrar.setText("Enviar Solicitud");
        btnRegistrar.addActionListener(this::btnRegistrarActionPerformed);

        btnVer.setText("Ver Solicitudes");
        btnVer.addActionListener(this::btnVerActionPerformed);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        label3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        label3.setText("Información de Solicitudes");

        jLabel5.setText("Id Cliente:");

        btnConsultar.setText("Consultar estado");
        btnConsultar.addActionListener(this::btnConsultarActionPerformed);

        jButton1.setText("Volver al Menu");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnRegistrar))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIdPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIdSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(220, 220, 220)
                                .addComponent(btnVer))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 495, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtConsultaId, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(89, 89, 89)
                        .addComponent(btnConsultar)))
                .addContainerGap(65, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(label3)
                .addGap(204, 204, 204))
            .addGroup(layout.createSequentialGroup()
                .addGap(266, 266, 266)
                .addComponent(label2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(label2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIdSolicitud, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtIdCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtIdPrestador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnVer))
                .addGap(18, 18, 18)
                .addComponent(label3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtConsultaId, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConsultar))
                .addContainerGap(59, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdPrestadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdPrestadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdPrestadorActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
        int idSol = Integer.parseInt(txtIdSolicitud.getText());
        String comentario = txtComentario.getText();
        String idCli = txtIdCliente.getText();
        String idPres = txtIdPrestador.getText();

        // 1. Buscar al cliente en el archivo de Clientes 
        umag.modelo.entidad.Cliente clienteEncontrado = null;
        try (java.io.ObjectInputStream ois = new java.io.ObjectInputStream(new java.io.FileInputStream("Clientes.dat"))) {
            java.util.List<umag.modelo.entidad.Cliente> clientes = (java.util.List<umag.modelo.entidad.Cliente>) ois.readObject();
            for (umag.modelo.entidad.Cliente c : clientes) {
                
                if (c.getId().equals(idCli)) { 
                    clienteEncontrado = c;
                    break;
                }
            }
        } catch (Exception e) {}

        // 2. Buscar al prestador en el archivo de Prestadores
        umag.modelo.entidad.Prestador prestadorEncontrado = null;
        try (java.io.ObjectInputStream ois = new java.io.ObjectInputStream(new java.io.FileInputStream("Prestadores.dat"))) { 
            java.util.List<umag.modelo.entidad.Prestador> prestadores = (java.util.List<umag.modelo.entidad.Prestador>) ois.readObject();
            for (umag.modelo.entidad.Prestador p : prestadores) {
                
                if (p.getId().equals(idPres)) { 
                    prestadorEncontrado = p;
                    break;
                }
            }
        } catch (Exception e) {}

        // 3. Validar y guardar
        if (clienteEncontrado != null && prestadorEncontrado != null) {
            umag.control.ControlSolicitud cs = new umag.control.ControlSolicitud();
            boolean guardado = cs.guardarSolicitud(idSol, comentario, clienteEncontrado, prestadorEncontrado);
            
            if(guardado){
                javax.swing.JOptionPane.showMessageDialog(this, "Solicitud registrada con éxito.");
                txtIdSolicitud.setText(""); txtComentario.setText(""); txtIdCliente.setText(""); txtIdPrestador.setText("");
            }
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: No se encontró el Cliente o el Prestador con esos IDs.");
        }

    } catch (NumberFormatException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "El ID de la solicitud debe ser un número entero.");
    }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        try {
        umag.modelo.persistencia.DaoSolicitud dao = new umag.modelo.persistencia.DaoSolicitud();
        
        // Usamos tu método listar()
        java.util.List<umag.modelo.entidad.Solicitud> solicitudes = dao.listar();
        
        // Cambia 'jTextArea1' por el nombre real de tu caja si le pusiste otro
        jTextArea1.setText(""); 
        
        if(solicitudes.isEmpty()){
            jTextArea1.append("No hay solicitudes registradas.\n");
        } else {
            for (umag.modelo.entidad.Solicitud s : solicitudes) {
                jTextArea1.append("---------------------------------------------------\n");
                jTextArea1.append(s.toString() + "\n");
            }
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al leer el archivo: " + e.getMessage());
    }
    }//GEN-LAST:event_btnVerActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String idBusqueda = txtConsultaId.getText();
    umag.modelo.persistencia.DaoSolicitud dao = new umag.modelo.persistencia.DaoSolicitud();
    try {
        java.util.List<umag.modelo.entidad.Solicitud> todas = dao.listar();
        jTextArea1.setText("--- MIS SOLICITUDES ---\n");
        boolean encontro = false;
        
        for (umag.modelo.entidad.Solicitud s : todas) {
            // Comparamos el ID del cliente de la solicitud con el ID que ingresó
            if (s.getCliente().getId().equals(idBusqueda)) {
                jTextArea1.append("Prestador: " + s.getPrestador().getNombre() + "\n");
                jTextArea1.append("Estado/Nota: " + s.getComentario() + "\n");
                jTextArea1.append("-----------------------------\n");
                encontro = true;
            }
        }
        if (!encontro) {
            jTextArea1.append("No tienes solicitudes con ese ID.");
        }
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Error al buscar: " + e.getMessage());
    }
    }//GEN-LAST:event_btnConsultarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVer;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JTextField txtComentario;
    private javax.swing.JTextField txtConsultaId;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtIdPrestador;
    private javax.swing.JTextField txtIdSolicitud;
    // End of variables declaration//GEN-END:variables
}
