/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package umag.vista;

/**
 *
 * @author LENOVO
 */
public class FormCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCliente.class.getName());

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblMascota = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblMetododepago = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        txtMascota = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtMetododepago = new javax.swing.JTextField();
        btnRegistrardatos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Datos Cliente");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 10, 110, 25);

        lblNombre.setText("Nombre:");
        getContentPane().add(lblNombre);
        lblNombre.setBounds(60, 60, 50, 16);

        txtNombre.addActionListener(this::txtNombreActionPerformed);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(120, 60, 200, 22);

        lblEmail.setText("Email:");
        getContentPane().add(lblEmail);
        lblEmail.setBounds(80, 180, 40, 20);
        getContentPane().add(txtTelefono);
        txtTelefono.setBounds(130, 270, 180, 22);

        lblId.setText("Id:");
        getContentPane().add(lblId);
        lblId.setBounds(90, 90, 30, 20);

        lblMascota.setText("Macota:");
        getContentPane().add(lblMascota);
        lblMascota.setBounds(70, 150, 50, 20);

        lblTelefono.setText("Telefono:");
        getContentPane().add(lblTelefono);
        lblTelefono.setBounds(70, 270, 80, 20);

        lblMetododepago.setText("Metodo de pago:");
        getContentPane().add(lblMetododepago);
        lblMetododepago.setBounds(30, 240, 110, 20);

        lblDireccion.setText("Direccion:");
        getContentPane().add(lblDireccion);
        lblDireccion.setBounds(60, 210, 60, 20);

        lblEdad.setText("Edad:");
        getContentPane().add(lblEdad);
        lblEdad.setBounds(80, 120, 30, 20);
        getContentPane().add(txtMascota);
        txtMascota.setBounds(120, 150, 90, 22);
        getContentPane().add(txtEmail);
        txtEmail.setBounds(120, 180, 190, 22);
        getContentPane().add(txtDireccion);
        txtDireccion.setBounds(120, 210, 190, 22);
        getContentPane().add(txtId);
        txtId.setBounds(120, 90, 150, 22);
        getContentPane().add(txtEdad);
        txtEdad.setBounds(120, 120, 50, 22);
        getContentPane().add(txtMetododepago);
        txtMetododepago.setBounds(130, 240, 130, 22);

        btnRegistrardatos.setText("Registrar datos");
        btnRegistrardatos.addActionListener(this::btnRegistrardatosActionPerformed);
        getContentPane().add(btnRegistrardatos);
        btnRegistrardatos.setBounds(140, 330, 120, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegistrardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrardatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrardatosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrardatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblMascota;
    private javax.swing.JLabel lblMetododepago;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMascota;
    private javax.swing.JTextField txtMetododepago;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtTelefono;
    // End of variables declaration//GEN-END:variables
}
