/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package umag.vista;

/**
 *
 * @author LENOVO
 */
public class FormCliente extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormCliente.class.getName());

    /**
     * Creates new form FormCliente
     */
    public FormCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblNombre = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        txtTelefono = new javax.swing.JTextField();
        lblId = new javax.swing.JLabel();
        lblMascota = new javax.swing.JLabel();
        lblTelefono = new javax.swing.JLabel();
        lblMetododepago = new javax.swing.JLabel();
        lblDireccion = new javax.swing.JLabel();
        lblEdad = new javax.swing.JLabel();
        txtMascota = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtId = new javax.swing.JTextField();
        txtEdad = new javax.swing.JTextField();
        txtMetododepago = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblNombre1 = new javax.swing.JLabel();
        txtNombre1 = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        txtTelefono1 = new javax.swing.JTextField();
        lblId1 = new javax.swing.JLabel();
        lblMascota1 = new javax.swing.JLabel();
        lblTelefono1 = new javax.swing.JLabel();
        lblMetododepago1 = new javax.swing.JLabel();
        lblDireccion1 = new javax.swing.JLabel();
        lblEdad1 = new javax.swing.JLabel();
        txtMascota1 = new javax.swing.JTextField();
        txtEmail1 = new javax.swing.JTextField();
        txtDireccion1 = new javax.swing.JTextField();
        txtId1 = new javax.swing.JTextField();
        txtEdad1 = new javax.swing.JTextField();
        txtMetododepago1 = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Datos Cliente");

        lblNombre.setText("Nombre:");

        txtNombre.addActionListener(this::txtNombreActionPerformed);

        lblEmail.setText("Email:");

        lblId.setText("Id:");

        lblMascota.setText("Macota:");

        lblTelefono.setText("Telefono:");

        lblMetododepago.setText("Metodo de pago:");

        lblDireccion.setText("Direccion:");

        lblEdad.setText("Edad:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Datos Cliente");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(170, 10, 110, 25);

        lblNombre1.setText("Nombre:");
        getContentPane().add(lblNombre1);
        lblNombre1.setBounds(60, 60, 50, 16);

        txtNombre1.addActionListener(this::txtNombre1ActionPerformed);
        getContentPane().add(txtNombre1);
        txtNombre1.setBounds(120, 60, 200, 22);

        lblEmail1.setText("Email:");
        getContentPane().add(lblEmail1);
        lblEmail1.setBounds(80, 180, 40, 20);
        getContentPane().add(txtTelefono1);
        txtTelefono1.setBounds(130, 270, 180, 22);

        lblId1.setText("Id:");
        getContentPane().add(lblId1);
        lblId1.setBounds(90, 90, 30, 20);

        lblMascota1.setText("Macota:");
        getContentPane().add(lblMascota1);
        lblMascota1.setBounds(70, 150, 50, 20);

        lblTelefono1.setText("Telefono:");
        getContentPane().add(lblTelefono1);
        lblTelefono1.setBounds(70, 270, 80, 20);

        lblMetododepago1.setText("Metodo de pago:");
        getContentPane().add(lblMetododepago1);
        lblMetododepago1.setBounds(30, 240, 110, 20);

        lblDireccion1.setText("Direccion:");
        getContentPane().add(lblDireccion1);
        lblDireccion1.setBounds(60, 210, 60, 20);

        lblEdad1.setText("Edad:");
        getContentPane().add(lblEdad1);
        lblEdad1.setBounds(80, 120, 30, 20);
        getContentPane().add(txtMascota1);
        txtMascota1.setBounds(120, 150, 90, 22);
        getContentPane().add(txtEmail1);
        txtEmail1.setBounds(120, 180, 190, 22);
        getContentPane().add(txtDireccion1);
        txtDireccion1.setBounds(120, 210, 190, 22);
        getContentPane().add(txtId1);
        txtId1.setBounds(120, 90, 150, 22);
        getContentPane().add(txtEdad1);
        txtEdad1.setBounds(120, 120, 50, 22);
        getContentPane().add(txtMetododepago1);
        txtMetododepago1.setBounds(130, 240, 130, 22);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreActionPerformed

    private void btnRegistrardatosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrardatosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrardatosActionPerformed

    private void txtNombre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombre1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombre1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormCliente().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDireccion;
    private javax.swing.JLabel lblDireccion1;
    private javax.swing.JLabel lblEdad;
    private javax.swing.JLabel lblEdad1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblMascota;
    private javax.swing.JLabel lblMascota1;
    private javax.swing.JLabel lblMetododepago;
    private javax.swing.JLabel lblMetododepago1;
    private javax.swing.JLabel lblNombre;
    private javax.swing.JLabel lblNombre1;
    private javax.swing.JLabel lblTelefono;
    private javax.swing.JLabel lblTelefono1;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDireccion1;
    private javax.swing.JTextField txtEdad;
    private javax.swing.JTextField txtEdad1;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtId1;
    private javax.swing.JTextField txtMascota;
    private javax.swing.JTextField txtMascota1;
    private javax.swing.JTextField txtMetododepago;
    private javax.swing.JTextField txtMetododepago1;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombre1;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTelefono1;
    // End of variables declaration//GEN-END:variables
}
